#ifndef ARRAYTYPE_H_
#include <stdint.h>
#include <stdarg.h>
#define ARRAYTYPE_H_
#define ARRAY_TYPE_SIGNED_INT 0x01
#define ARRAY_TYPE_UNSIGNED_INT 0x02
#define ARRAY_TYPE_SIGNED_SHORT 0x03
#define ARRAY_TYPE_UNSIGNED_SHORT 0x04
#define ARRAY_TYPE_SIGNED_LONG 0x05
#define ARRAY_TYPE_UNSIGNED_LONG 0x06
#define ARRAY_TYPE_SIGNED_LONG_LONG 0x07
#define ARRAY_TYPE_UNSIGNED_LONG_LONG 0x08
#define ARRAY_TYPE_SIGNED_CHAR 0x09
#define ARRAY_TYPE_UNSIGNED_CHAR 0x0a
#define ARRAY_TYPE_CHAR 0x0b
#define ARRAY_TYPE_DOUBLE 0x0c
#define ARRAY_TYPE_FLOAT 0x0d
#define ARRAY_TYPE_POINTER 0x0e
#endif /* ARRAYTYPE_H_ */